# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {HDL-1065} -limit 10000
set_msg_config  -ruleid {7}  -id {[BD 41-1306]}  -suppress 
set_msg_config  -ruleid {8}  -id {[BD 41-1271]}  -suppress 
create_project -in_memory -part xcku115-flvb2104-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir F:/JUYG/PCIe_setup_DRAM_rev1/project_1.cache/wt [current_project]
set_property parent.project_path F:/JUYG/PCIe_setup_DRAM_rev1/project_1.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:kcu1500:part0:1.1 [current_project]
set_property ip_output_repo f:/JUYG/PCIe_setup_DRAM_rev1/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib F:/JUYG/PCIe_setup_DRAM_rev1/project_1.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.v
add_files F:/JUYG/PCIe_setup_DRAM_rev1/project_1.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all f:/JUYG/PCIe_setup_DRAM_rev1/project_1.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/design_1_ddr4_0_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/JUYG/PCIe_setup_DRAM_rev1/project_1.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/par/design_1_ddr4_0_0.xdc]
set_property used_in_implementation false [get_files -all f:/JUYG/PCIe_setup_DRAM_rev1/project_1.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/bd_0/ip/ip_0/bd_45eb_microblaze_I_0.xdc]
set_property used_in_implementation false [get_files -all f:/JUYG/PCIe_setup_DRAM_rev1/project_1.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/bd_0/ip/ip_0/bd_45eb_microblaze_I_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all f:/JUYG/PCIe_setup_DRAM_rev1/project_1.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/bd_0/ip/ip_1/bd_45eb_rst_0_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/JUYG/PCIe_setup_DRAM_rev1/project_1.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/bd_0/ip/ip_1/bd_45eb_rst_0_0.xdc]
set_property used_in_implementation false [get_files -all f:/JUYG/PCIe_setup_DRAM_rev1/project_1.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/bd_0/ip/ip_2/bd_45eb_ilmb_0.xdc]
set_property used_in_implementation false [get_files -all f:/JUYG/PCIe_setup_DRAM_rev1/project_1.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/bd_0/ip/ip_3/bd_45eb_dlmb_0.xdc]
set_property used_in_implementation false [get_files -all f:/JUYG/PCIe_setup_DRAM_rev1/project_1.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/bd_0/ip/ip_6/bd_45eb_lmb_bram_I_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/JUYG/PCIe_setup_DRAM_rev1/project_1.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/bd_0/ip/ip_9/bd_45eb_second_lmb_bram_I_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/JUYG/PCIe_setup_DRAM_rev1/project_1.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/bd_0/ip/ip_10/bd_45eb_iomodule_0_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/JUYG/PCIe_setup_DRAM_rev1/project_1.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/bd_0/bd_45eb_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/JUYG/PCIe_setup_DRAM_rev1/project_1.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/ip_0/design_1_ddr4_0_0_microblaze_mcs_board.xdc]
set_property used_in_implementation false [get_files -all f:/JUYG/PCIe_setup_DRAM_rev1/project_1.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/ip_0/design_1_ddr4_0_0_microblaze_mcs_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/JUYG/PCIe_setup_DRAM_rev1/project_1.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/ip_1/par/design_1_ddr4_0_0_phy_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/JUYG/PCIe_setup_DRAM_rev1/project_1.srcs/sources_1/bd/design_1/ip/design_1_xdma_0_0/ip_0/ip_0/synth/design_1_xdma_0_0_pcie3_ip_gt_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/JUYG/PCIe_setup_DRAM_rev1/project_1.srcs/sources_1/bd/design_1/ip/design_1_xdma_0_0/ip_0/ip_0/synth/design_1_xdma_0_0_pcie3_ip_gt.xdc]
set_property used_in_implementation false [get_files -all f:/JUYG/PCIe_setup_DRAM_rev1/project_1.srcs/sources_1/bd/design_1/ip/design_1_xdma_0_0/ip_0/source/design_1_xdma_0_0_pcie3_ip-PCIE_X0Y0.xdc]
set_property used_in_implementation false [get_files -all f:/JUYG/PCIe_setup_DRAM_rev1/project_1.srcs/sources_1/bd/design_1/ip/design_1_xdma_0_0/ip_0/synth/design_1_xdma_0_0_pcie3_ip_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/JUYG/PCIe_setup_DRAM_rev1/project_1.srcs/sources_1/bd/design_1/ip/design_1_xdma_0_0/ip_1/xdma_v4_0_1_blk_mem_64_reg_be_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/JUYG/PCIe_setup_DRAM_rev1/project_1.srcs/sources_1/bd/design_1/ip/design_1_xdma_0_0/ip_2/xdma_v4_0_1_blk_mem_64_noreg_be_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/JUYG/PCIe_setup_DRAM_rev1/project_1.srcs/sources_1/bd/design_1/ip/design_1_xdma_0_0/design_1_xdma_0_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/JUYG/PCIe_setup_DRAM_rev1/project_1.srcs/sources_1/bd/design_1/ip/design_1_xdma_0_0/source/design_1_xdma_0_0_pcie3_us_ip.xdc]
set_property used_in_implementation false [get_files -all f:/JUYG/PCIe_setup_DRAM_rev1/project_1.srcs/sources_1/bd/design_1/ip/design_1_xdma_0_0/synth/design_1_xdma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/JUYG/PCIe_setup_DRAM_rev1/project_1.srcs/sources_1/bd/design_1/ip/design_1_util_ds_buf_0/design_1_util_ds_buf_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/JUYG/PCIe_setup_DRAM_rev1/project_1.srcs/sources_1/bd/design_1/ip/design_1_util_ds_buf_0/design_1_util_ds_buf_0.xdc]
set_property used_in_implementation false [get_files -all f:/JUYG/PCIe_setup_DRAM_rev1/project_1.srcs/sources_1/bd/design_1/ip/design_1_util_ds_buf_0/design_1_util_ds_buf_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/JUYG/PCIe_setup_DRAM_rev1/project_1.srcs/sources_1/bd/design_1/ip/design_1_rst_ddr4_0_300M_1/design_1_rst_ddr4_0_300M_1_board.xdc]
set_property used_in_implementation false [get_files -all f:/JUYG/PCIe_setup_DRAM_rev1/project_1.srcs/sources_1/bd/design_1/ip/design_1_rst_ddr4_0_300M_1/design_1_rst_ddr4_0_300M_1.xdc]
set_property used_in_implementation false [get_files -all f:/JUYG/PCIe_setup_DRAM_rev1/project_1.srcs/sources_1/bd/design_1/ip/design_1_rst_ddr4_0_300M_1/design_1_rst_ddr4_0_300M_1_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/JUYG/PCIe_setup_DRAM_rev1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_1/design_1_axi_gpio_0_1_board.xdc]
set_property used_in_implementation false [get_files -all f:/JUYG/PCIe_setup_DRAM_rev1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_1/design_1_axi_gpio_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/JUYG/PCIe_setup_DRAM_rev1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_1/design_1_axi_gpio_0_1.xdc]
set_property used_in_implementation false [get_files -all f:/JUYG/PCIe_setup_DRAM_rev1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_bram_ctrl_0_1/design_1_axi_bram_ctrl_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/JUYG/PCIe_setup_DRAM_rev1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_bram_ctrl_0_bram_0/design_1_axi_bram_ctrl_0_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/JUYG/PCIe_setup_DRAM_rev1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_bram_ctrl_1_1/design_1_axi_bram_ctrl_1_1_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/JUYG/PCIe_setup_DRAM_rev1/project_1.srcs/sources_1/bd/design_1/ip/design_1_blk_mem_gen_0_0/design_1_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/JUYG/PCIe_setup_DRAM_rev1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_bram_ctrl_1_0/design_1_axi_bram_ctrl_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/JUYG/PCIe_setup_DRAM_rev1/project_1.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/design_1_xbar_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all f:/JUYG/PCIe_setup_DRAM_rev1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_0/design_1_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all f:/JUYG/PCIe_setup_DRAM_rev1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_0/design_1_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all f:/JUYG/PCIe_setup_DRAM_rev1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_0/design_1_auto_ds_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all f:/JUYG/PCIe_setup_DRAM_rev1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_us_0/design_1_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all f:/JUYG/PCIe_setup_DRAM_rev1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_us_0/design_1_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all f:/JUYG/PCIe_setup_DRAM_rev1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_us_0/design_1_auto_us_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all f:/JUYG/PCIe_setup_DRAM_rev1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_cc_0/design_1_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all f:/JUYG/PCIe_setup_DRAM_rev1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_cc_0/design_1_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all f:/JUYG/PCIe_setup_DRAM_rev1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_cc_0/design_1_auto_cc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all F:/JUYG/PCIe_setup_DRAM_rev1/project_1.srcs/sources_1/bd/design_1/design_1_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top design_1_wrapper -part xcku115-flvb2104-2-e


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef design_1_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb"
